theory Open_Theory
imports Pure
begin

SML_import \<open>
structure PolyML = struct
  val pointerEq = pointer_eq
end

structure OS = struct
  open OS
  structure Process = struct
    open OS.Process
    exception Exit of OS.Process.status
    fun exit status = raise Exit status
  end
end

structure TextIO = struct
  open TextIO
  fun output (_, s) = writeln s
end
\<close>

SML_file "opentheory/src/Random.sig"
SML_file "opentheory/src/Random.sml"
SML_file "opentheory/src/Portable.sig"
SML_file "opentheory/src/PortablePolyml.sml"
SML_file "opentheory/src/Useful.sig"
SML_file "opentheory/src/Useful.sml"
SML_file "opentheory/src/Lazy.sig"
SML_file "opentheory/src/Lazy.sml"
SML_file "opentheory/src/Ordered.sig"
SML_file "opentheory/src/Ordered.sml"
SML_file "opentheory/src/Map.sig"
SML_file "opentheory/src/Map.sml"
SML_file "opentheory/src/KeyMap.sig"
SML_file "opentheory/src/KeyMap.sml"
SML_file "opentheory/src/Set.sig"
SML_file "opentheory/src/Set.sml"
SML_file "opentheory/src/ElementSet.sig"
SML_file "opentheory/src/ElementSet.sml"
SML_file "opentheory/src/VertexGraph.sig"
SML_file "opentheory/src/VertexGraph.sml"
SML_file "opentheory/src/Stream.sig"
SML_file "opentheory/src/Stream.sml"
SML_file "opentheory/src/Queue.sig"
SML_file "opentheory/src/Queue.sml"
SML_file "opentheory/src/Heap.sig"
SML_file "opentheory/src/Heap.sml"
SML_file "opentheory/src/Print.sig"
SML_file "opentheory/src/Print.sml"
SML_file "opentheory/src/Parse.sig"
SML_file "opentheory/src/Parse.sml"
SML_file "opentheory/src/Html.sig"
SML_file "opentheory/src/Html.sml"
SML_file "opentheory/src/Config.sig"
SML_file "opentheory/src/Config.sml"
SML_file "opentheory/src/Checksum.sig"
SML_file "opentheory/src/Checksum.sml"
SML_file "opentheory/src/Namespace.sig"
SML_file "opentheory/src/Namespace.sml"
SML_file "opentheory/src/Name.sig"
SML_file "opentheory/src/Name.sml"
SML_file "opentheory/src/Metadata.sig"
SML_file "opentheory/src/Metadata.sml"
SML_file "opentheory/src/Show.sig"
SML_file "opentheory/src/Show.sml"
SML_file "opentheory/src/TypeTerm.sig"
SML_file "opentheory/src/TypeTerm.sml"
SML_file "opentheory/src/TypeOp.sig"
SML_file "opentheory/src/TypeOp.sml"
SML_file "opentheory/src/Type.sig"
SML_file "opentheory/src/Type.sml"
SML_file "opentheory/src/TypeRewrite.sig"
SML_file "opentheory/src/TypeRewrite.sml"
SML_file "opentheory/src/TypeSubst.sig"
SML_file "opentheory/src/TypeSubst.sml"
SML_file "opentheory/src/Var.sig"
SML_file "opentheory/src/Var.sml"
SML_file "opentheory/src/Const.sig"
SML_file "opentheory/src/Const.sml"
SML_file "opentheory/src/Term.sig"
SML_file "opentheory/src/Term.sml"
SML_file "opentheory/src/TermRewrite.sig"
SML_file "opentheory/src/TermRewrite.sml"
SML_file "opentheory/src/TermSearch.sig"
SML_file "opentheory/src/TermSearch.sml"
SML_file "opentheory/src/TermSubst.sig"
SML_file "opentheory/src/TermSubst.sml"
SML_file "opentheory/src/Sequent.sig"
SML_file "opentheory/src/Sequent.sml"
SML_file "opentheory/src/Thm.sig"
SML_file "opentheory/src/Thm.sml"
SML_file "opentheory/src/Symbol.sig"
SML_file "opentheory/src/Symbol.sml"
SML_file "opentheory/src/SymbolTable.sig"
SML_file "opentheory/src/SymbolTable.sml"
SML_file "opentheory/src/Rule.sig"
SML_file "opentheory/src/Rule.sml"
SML_file "opentheory/src/Thms.sig"
SML_file "opentheory/src/Thms.sml"
SML_file "opentheory/src/Sequents.sig"
SML_file "opentheory/src/Sequents.sml"
SML_file "opentheory/src/Summary.sig"
SML_file "opentheory/src/Summary.sml"
SML_file "opentheory/src/Interpretation.sig"
SML_file "opentheory/src/Interpretation.sml"
SML_file "opentheory/src/Command.sig"
SML_file "opentheory/src/Command.sml"
SML_file "opentheory/src/ArticleVersion.sig"
SML_file "opentheory/src/ArticleVersion.sml"
SML_file "opentheory/src/Inference.sig"
SML_file "opentheory/src/Inference.sml"
SML_file "opentheory/src/ObjectData.sig"
SML_file "opentheory/src/ObjectData.sml"
SML_file "opentheory/src/Object.sig"
SML_file "opentheory/src/Object.sml"
SML_file "opentheory/src/ObjectStore.sig"
SML_file "opentheory/src/ObjectStore.sml"
SML_file "opentheory/src/ObjectSymbol.sig"
SML_file "opentheory/src/ObjectSymbol.sml"
SML_file "opentheory/src/ObjectRewrite.sig"
SML_file "opentheory/src/ObjectRewrite.sml"
SML_file "opentheory/src/ObjectRename.sig"
SML_file "opentheory/src/ObjectRename.sml"
SML_file "opentheory/src/ObjectUnwanted.sig"
SML_file "opentheory/src/ObjectUnwanted.sml"
SML_file "opentheory/src/ObjectSkipDefinitions.sig"
SML_file "opentheory/src/ObjectSkipDefinitions.sml"
SML_file "opentheory/src/ObjectVersion.sig"
SML_file "opentheory/src/ObjectVersion.sml"
SML_file "opentheory/src/ObjectThm.sig"
SML_file "opentheory/src/ObjectThm.sml"
SML_file "opentheory/src/ObjectExport.sig"
SML_file "opentheory/src/ObjectExport.sml"
SML_file "opentheory/src/ObjectThms.sig"
SML_file "opentheory/src/ObjectThms.sml"
SML_file "opentheory/src/ObjectDict.sig"
SML_file "opentheory/src/ObjectDict.sml"
SML_file "opentheory/src/ObjectStack.sig"
SML_file "opentheory/src/ObjectStack.sml"
SML_file "opentheory/src/ObjectRead.sig"
SML_file "opentheory/src/ObjectRead.sml"
SML_file "opentheory/src/ObjectWrite.sig"
SML_file "opentheory/src/ObjectWrite.sml"
SML_file "opentheory/src/ObjectTheorems.sig"
SML_file "opentheory/src/ObjectTheorems.sml"
SML_file "opentheory/src/Article.sig"
SML_file "opentheory/src/Article.sml"
SML_file "opentheory/src/PackageName.sig"
SML_file "opentheory/src/PackageName.sml"
SML_file "opentheory/src/PackageVersion.sig"
SML_file "opentheory/src/PackageVersion.sml"
SML_file "opentheory/src/PackageNameVersion.sig"
SML_file "opentheory/src/PackageNameVersion.sml"
SML_file "opentheory/src/PackageAuthor.sig"
SML_file "opentheory/src/PackageAuthor.sml"
SML_file "opentheory/src/PackageInterpretation.sig"
SML_file "opentheory/src/PackageInterpretation.sml"
SML_file "opentheory/src/PackageSummary.sig"
SML_file "opentheory/src/PackageSummary.sml"
SML_file "opentheory/src/PackageTheory.sig"
SML_file "opentheory/src/PackageTheory.sml"
SML_file "opentheory/src/PackageExtra.sig"
SML_file "opentheory/src/PackageExtra.sml"
SML_file "opentheory/src/PackageTag.sig"
SML_file "opentheory/src/PackageTag.sml"
SML_file "opentheory/src/PackageInformation.sig"
SML_file "opentheory/src/PackageInformation.sml"
SML_file "opentheory/src/RepositorySystem.sig"
SML_file "opentheory/src/RepositorySystem.sml"
SML_file "opentheory/src/PackageTarball.sig"
SML_file "opentheory/src/PackageTarball.sml"
SML_file "opentheory/src/PackageTheorems.sig"
SML_file "opentheory/src/PackageTheorems.sml"
SML_file "opentheory/src/PackageDocument.sig"
SML_file "opentheory/src/PackageDocument.sml"
SML_file "opentheory/src/Package.sig"
SML_file "opentheory/src/Package.sml"
SML_file "opentheory/src/PackageDependency.sig"
SML_file "opentheory/src/PackageDependency.sml"
SML_file "opentheory/src/PackageFinder.sig"
SML_file "opentheory/src/PackageFinder.sml"
SML_file "opentheory/src/Theory.sig"
SML_file "opentheory/src/Theory.sml"
SML_file "opentheory/src/TheoryName.sig"
SML_file "opentheory/src/TheoryName.sml"
SML_file "opentheory/src/TheoryGraph.sig"
SML_file "opentheory/src/TheoryGraph.sml"
SML_file "opentheory/src/PackageTheoryGraph.sig"
SML_file "opentheory/src/PackageTheoryGraph.sml"
SML_file "opentheory/src/RepositoryChecksums.sig"
SML_file "opentheory/src/RepositoryChecksums.sml"
SML_file "opentheory/src/RepositoryPath.sig"
SML_file "opentheory/src/RepositoryPath.sml"
SML_file "opentheory/src/RepositoryRemote.sig"
SML_file "opentheory/src/RepositoryRemote.sml"
SML_file "opentheory/src/RepositoryPackages.sig"
SML_file "opentheory/src/RepositoryPackages.sml"
SML_file "opentheory/src/RepositoryError.sig"
SML_file "opentheory/src/RepositoryError.sml"
SML_file "opentheory/src/RepositoryConfig.sig"
SML_file "opentheory/src/RepositoryConfig.sml"
SML_file "opentheory/src/Repository.sig"
SML_file "opentheory/src/Repository.sml"
SML_file "opentheory/src/RepositoryUpload.sig"
SML_file "opentheory/src/RepositoryUpload.sml"
SML_file "opentheory/src/Haskell.sig"
SML_file "opentheory/src/Haskell.sml"
SML_file "opentheory/src/RepositoryQuery.sig"
SML_file "opentheory/src/RepositoryQuery.sml"
SML_file "opentheory/src/Syntax.sig"
SML_file "opentheory/src/Syntax.sml"
SML_file "opentheory/src/Options.sig"
SML_file "opentheory/src/Options.sml"
SML_file "opentheory/src/Tool.sig"
SML_file "opentheory/src/Tool.sml"

SML_export \<open>structure Open_Theory = Tool\<close>

end